"""add auto_sync to social_connections

Revision ID: 407ce83b37e3
Revises: 1aeb68c46273
Create Date: 2026-03-11 20:24:17.635488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '407ce83b37e3'
down_revision: Union[str, None] = '1aeb68c46273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_connections', sa.Column('auto_sync', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_connections', 'auto_sync')
    # ### end Alembic commands ###
