"""Add persona and image_context

Revision ID: 4b6058396564
Revises: 
Create Date: 2026-02-23 19:19:39.042257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b6058396564'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'author_id_platform')
    op.drop_column('comments', 'ingest_source')
    op.add_column('posts', sa.Column('image_context', sa.Text(), nullable=True))
    op.drop_column('posts', 'save_count')
    op.drop_column('posts', 'location_name')
    op.drop_column('posts', 'video_duration')
    op.drop_column('posts', 'mentions')
    op.drop_column('posts', 'hashtags')
    op.drop_column('posts', 'thumbnail_url')
    op.drop_column('posts', 'is_video')
    op.drop_column('posts', 'ingest_source')
    op.add_column('social_connections', sa.Column('persona', sa.Text(), nullable=True))
    op.drop_column('social_connections', 'is_verified')
    op.drop_column('social_connections', 'biography')
    op.drop_column('social_connections', 'media_count')
    op.drop_column('social_connections', 'external_url')
    op.drop_column('social_connections', 'is_private')
    op.drop_column('social_connections', 'following_count')
    op.drop_column('social_connections', 'ingest_source')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_connections', sa.Column('ingest_source', sa.VARCHAR(length=50), server_default=sa.text("'apify'::character varying"), autoincrement=False, nullable=True))
    op.add_column('social_connections', sa.Column('following_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('social_connections', sa.Column('is_private', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('social_connections', sa.Column('external_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('social_connections', sa.Column('media_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('social_connections', sa.Column('biography', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('social_connections', sa.Column('is_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_column('social_connections', 'persona')
    op.add_column('posts', sa.Column('ingest_source', sa.VARCHAR(length=50), server_default=sa.text("'apify'::character varying"), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('is_video', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('thumbnail_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('hashtags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('mentions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('video_duration', sa.REAL(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('location_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('save_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.drop_column('posts', 'image_context')
    op.add_column('comments', sa.Column('ingest_source', sa.VARCHAR(length=50), server_default=sa.text("'apify'::character varying"), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('author_id_platform', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
