"""add commenter_profiles and user_enrichments tables

Revision ID: a2d688105e98
Revises: 1d7bae8d13bb
Create Date: 2026-03-17 02:58:59.519680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a2d688105e98'
down_revision: Union[str, None] = '1d7bae8d13bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_enrichments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('gender_confidence', sa.Float(), nullable=True),
    sa.Column('age_band', sa.String(length=20), nullable=True),
    sa.Column('age_confidence', sa.Float(), nullable=True),
    sa.Column('location_country', sa.String(length=100), nullable=True),
    sa.Column('location_state', sa.String(length=100), nullable=True),
    sa.Column('location_city', sa.String(length=255), nullable=True),
    sa.Column('location_confidence', sa.Float(), nullable=True),
    sa.Column('location_source', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('inferred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_llm_response', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['social_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['commenter_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'connection_id', name='uq_profile_connection_enrichment')
    )
    op.create_index(op.f('ix_user_enrichments_connection_id'), 'user_enrichments', ['connection_id'], unique=False)
    op.create_index(op.f('ix_user_enrichments_profile_id'), 'user_enrichments', ['profile_id'], unique=False)
    op.drop_index(op.f('idx_ue_age'), table_name='user_enrichment')
    op.drop_index(op.f('idx_ue_country'), table_name='user_enrichment')
    op.drop_index(op.f('idx_ue_gender'), table_name='user_enrichment')
    op.drop_index(op.f('idx_ue_username'), table_name='user_enrichment')
    op.drop_table('user_enrichment')
    op.add_column('commenter_profiles', sa.Column('platform', sa.String(length=50), nullable=False, server_default='instagram'))
    op.add_column('commenter_profiles', sa.Column('display_name', sa.String(length=255), nullable=True))
    op.add_column('commenter_profiles', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('commenter_profiles', sa.Column('follower_count', sa.Integer(), nullable=True))
    op.add_column('commenter_profiles', sa.Column('post_count', sa.Integer(), nullable=True))
    op.add_column('commenter_profiles', sa.Column('is_private', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('commenter_profiles', sa.Column('is_verified', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('commenter_profiles', sa.Column('profile_pic_url', sa.Text(), nullable=True))
    op.add_column('commenter_profiles', sa.Column('external_url', sa.Text(), nullable=True))
    op.add_column('commenter_profiles', sa.Column('latest_posts_geo', sa.JSON(), nullable=True))
    op.add_column('commenter_profiles', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    op.add_column('commenter_profiles', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    # Migrate data from old columns to new columns
    op.execute("""
        UPDATE commenter_profiles SET
            display_name = full_name,
            bio = biography,
            follower_count = followers_count,
            profile_pic_url = profile_pic_url_hd,
            external_url = website
    """)

    op.alter_column('commenter_profiles', 'raw_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_constraint(op.f('commenter_profiles_username_key'), 'commenter_profiles', type_='unique')
    op.drop_index(op.f('idx_cp_username'), table_name='commenter_profiles')
    op.create_index(op.f('ix_commenter_profiles_username'), 'commenter_profiles', ['username'], unique=True)
    op.drop_column('commenter_profiles', 'website')
    op.drop_column('commenter_profiles', 'followers_count')
    op.drop_column('commenter_profiles', 'profile_pic_url_hd')
    op.drop_column('commenter_profiles', 'biography')
    op.drop_column('commenter_profiles', 'location_field')
    op.drop_column('commenter_profiles', 'is_business')
    op.drop_column('commenter_profiles', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commenter_profiles', sa.Column('full_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('commenter_profiles', sa.Column('is_business', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('commenter_profiles', sa.Column('location_field', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('commenter_profiles', sa.Column('biography', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('commenter_profiles', sa.Column('profile_pic_url_hd', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('commenter_profiles', sa.Column('followers_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('commenter_profiles', sa.Column('website', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_commenter_profiles_username'), table_name='commenter_profiles')
    op.create_index(op.f('idx_cp_username'), 'commenter_profiles', ['username'], unique=False)
    op.create_unique_constraint(op.f('commenter_profiles_username_key'), 'commenter_profiles', ['username'], postgresql_nulls_not_distinct=False)
    op.alter_column('commenter_profiles', 'raw_payload',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('commenter_profiles', 'updated_at')
    op.drop_column('commenter_profiles', 'created_at')
    op.drop_column('commenter_profiles', 'latest_posts_geo')
    op.drop_column('commenter_profiles', 'external_url')
    op.drop_column('commenter_profiles', 'profile_pic_url')
    op.drop_column('commenter_profiles', 'is_verified')
    op.drop_column('commenter_profiles', 'is_private')
    op.drop_column('commenter_profiles', 'post_count')
    op.drop_column('commenter_profiles', 'follower_count')
    op.drop_column('commenter_profiles', 'bio')
    op.drop_column('commenter_profiles', 'display_name')
    op.drop_column('commenter_profiles', 'platform')
    op.create_table('user_enrichment',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('gender_label', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('gender_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('age_band', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('age_estimated', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('age_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('location_country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('location_country_code', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('location_country_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('location_state', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('location_state_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('location_city', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('location_city_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('source_model', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('had_photo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('had_bio', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('had_location_field', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('evidence_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('computed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_enrichment_pkey')),
    sa.UniqueConstraint('username', name=op.f('user_enrichment_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_ue_username'), 'user_enrichment', ['username'], unique=False)
    op.create_index(op.f('idx_ue_gender'), 'user_enrichment', ['gender_label'], unique=False)
    op.create_index(op.f('idx_ue_country'), 'user_enrichment', ['location_country_code'], unique=False)
    op.create_index(op.f('idx_ue_age'), 'user_enrichment', ['age_band'], unique=False)
    op.drop_index(op.f('ix_user_enrichments_profile_id'), table_name='user_enrichments')
    op.drop_index(op.f('ix_user_enrichments_connection_id'), table_name='user_enrichments')
    op.drop_table('user_enrichments')
    # ### end Alembic commands ###
